"""update db

Revision ID: 74f2295e7e5d
Revises: ebf540e373a1
Create Date: 2024-03-29 11:21:08.249908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f2295e7e5d'
down_revision: Union[str, None] = 'ebf540e373a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('profile', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint('profile_username_key', 'profile', type_='unique')
    op.drop_column('profile', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_unique_constraint('profile_username_key', 'profile', ['username'])
    op.alter_column('profile', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('profile', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
